#ifndef OM_LOG_H
#define OM_LOG_H

#define ARQWALLET_LOG_CATEGORY "arq_wallet"

#define OMINFO  CLOG(INFO, ARQWALLET_LOG_CATEGORY)
#define OMWARN  CLOG(WARNING, ARQWALLET_LOG_CATEGORY)
#define OMERROR CLOG(ERROR, ARQWALLET_LOG_CATEGORY)

#define OMINFO_IF(cond)  CLOG_IF(cond, INFO, ARQWALLET_LOG_CATEGORY)
#define OMWARN_IF(cond)  CLOG_IF(cond, WARNING, ARQWALLET_LOG_CATEGORY)
#define OMERROR_IF(cond) CLOG_IF(cond, ERROR, ARQWALLET_LOG_CATEGORY)


#endif // OM_LOG_H
